# Generated by Django 3.1.7 on 2021-05-25 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization_demo',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 20, 36, 46, 401116), verbose_name='date published'),
        ),
    ]
