# Generated by Django 3.1.7 on 2021-05-25 21:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210525_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization_demo',
            name='content',
            field=models.TextField(default=datetime.datetime(2021, 5, 25, 21, 13, 55, 275525, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visualization_demo',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 22, 11, 9, 778576), verbose_name='date published'),
        ),
    ]
