# Generated by Django 3.1.7 on 2021-05-26 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210525_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization_demo',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 15, 6, 35, 102505), verbose_name='date published'),
        ),
    ]
