# Generated by Django 3.1.7 on 2021-05-26 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210526_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization_demo',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 16, 51, 54, 417534), verbose_name='date published'),
        ),
    ]
