# Generated by Django 3.1.7 on 2021-05-26 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210526_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization_demo',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 17, 5, 34, 795350), verbose_name='date published'),
        ),
    ]
